version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_TESGITALL_8925Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_tesgitall_8925.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_TESGITALL_8925Project
    version: "1.0"
- serviceName: project.siqa_tesgitall_8925.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_TESGITALL_8925Project
    version: "1.0"
